name: CI

on:
  push:
  pull_request:

jobs:
  moon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: moonbitlang/setup-moonbit@v1

      - name: moon check
        run: moon check

      - name: moon test
        run: moon test

      - name: moon fmt --check
        run: moon fmt --check
